### PR TITLE
fix nil exception

### PR DESCRIPTION
**Pull request by zhuangjinjin**
**What this PR does**:
fix nil exception when exec command error

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wongoo** [comment]
@zhuangjinjin how nil exception happens, can u provide more detail about it ?

**Comment by wongoo** [comment]
@zhuangjinjin  the ci failed, u need to run `make format` to format the code

**Comment by zhuangjinjin** [comment]
> @zhuangjinjin the ci failed, u need to run `make format` to format the code

ok, I'm try later

**Comment by zhuangjinjin** [comment]
> @zhuangjinjin how nil exception happens, can u provide more detail about it ?

I have config.json like this

`
{
    "port":54330,
    "servers":[
        {
            "id":"test",
            "command_gen":"./echo_tail_pods.sh"
        }
    ]
}
`
echo_tail_pods.sh like this
`
cmd='docker ps'
echo "$cmd"
`
and then I run this application with argument '-file ./config.json', it crash. 

image

**Review by wongoo — APPROVED** [review]
LGTM

**Comment by wongoo** [comment]
@zhuangjinjin `make check` error need to fix, pls

**Pull request merged**
